### ISSUE TITLE
Please recompile with CMake option -DUSE_GPU=1

### ISSUE THREAD

**Issue by pseudotensor** [dask/dask-lightgbm#22]
```
[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
distributed.worker - WARNING -  Compute Failed
```

If I try to use GPUs I get this message, even though my base lightgbm was compiled with GPUs and non-dask models work fine.

Is this expected?

**Comment by SfinxCZ** [comment]
Closing this issue, since this repo is no longer maintained and the code itself is now part of the lightgbm library (https://github.com/microsoft/LightGBM). In case that this issue is still relevant, recreate please this issue in the LightGBM repository.
