### ISSUE TITLE
Program blocks for a long time 

### ISSUE THREAD

**Issue by Dinxin** [dask/dask-lightgbm#25]
`import os  
import dask.dataframe as dd  
from dask.distributed import Client 
import dask_lightgbm.core as dlgbm 
import logging 

logging.basicConfig(format='%(asctime)s, %(message)s', level=logging.INFO)
listen_port = 12400

def make_client():
    return Client('127.0.0.1:51127')

def test_classify_newsread(client, listen_port):
    logging.info("Read data ...")
    data = dd.read_csv('./system_tests/data/*.gz', compression='gzip', blocksize=None)
    dX = data.iloc[:, :-1]
    dy = data.iloc[:, -1] 

    logging.info("Train classifier ...")
    d_classif = dlgbm.LGBMClassifier(n_estimators=50, local_listen_port=listen_port)
    d_classif.fit(dX, dy) 

    logging.info("Predict ...")
    dy_pred = d_classif.predict(dX, client=client)

    logging.info("Evaluate metrics ...")
    acc_score = (dy == dy_pred).sum() / len(dy)
    acc_score = acc_score.compute()
    print(acc_score)

    assert acc_score > 0.8 

test_classify_newsread(make_client(), listen_port)`

I launched a dask.distributed.Client object in '127.0.0.1:51127'. But the program cannot come to an end. 

![image](https://user-images.githubusercontent.com/19572535/100433226-bbb06900-30d5-11eb-860c-24eb91f829f8.png)

**Comment by SfinxCZ** [comment]
Closing this issue, since this repo is no longer maintained and the code itself is now part of the lightgbm library (https://github.com/microsoft/LightGBM). Please recreate this issue in the LightGBM repository.
