### ISSUE TITLE
Final release

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask-lightgbm#31]
In https://github.com/dask/dask-lightgbm/pull/30 we added a warning that `dask-lightgbm` is deprecated. It would be great to issue one final release with this change before archiving this repo.

@SfinxCZ I'm not sure what your availability is for pushing out such a release. If you'd prefer for me to handle the release, I'm happy to do so, could you add me to the dask-lightgbm project on PyPI? My PyPI username is the same as my GitHub username

**Comment by jameslamb** [comment]
gently ping @SfinxCZ . I see `dask-lightgbm` is still on 0.1.0: https://pypi.org/project/dask-lightgbm/#history.

I think it would help to reduce some confusion for people newly exploring the use of Dask + LightGBM if we could do a final release of `dask-lightgbm` and then archive this repo.

**Comment by SfinxCZ** [comment]
Sorry for delay, I've published version 0.2.0 to PyPI that contains deprecation warning.

**Comment by jrbourbeau** [comment]
Thanks @SfinxCZ! I'll go ahead and close this issue and then archive this repository then
