### ISSUE TITLE
MPI support

### ISSUE THREAD

**Issue by guolinke** [dask/dask-lightgbm#4]
As LightGBM supports MPI itself, is that possible to use MPI for high-performance communication in dask?

**Comment by SfinxCZ** [comment]
Thanks for question.

I am not sure that supporting MPI in this package is best idea. This package should be used in case that you use dask for all data loading/preprocessing. In case that you want to use LightGBM with MPI, it is probably better not to use dask and use MPI directly and not use dask at all. 

In case that you want to discuss MPI support in dask, you can ask the question in dask project directly. This repo deals with the dask-LightGBM integration only.
